# Generated by Django 2.2.7 on 2019-11-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Nombre del campus')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Empleado')),
                ('cedula', models.CharField(max_length=11, verbose_name='Cedula')),
                ('tanda_labor', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=50, verbose_name='Tanda')),
                ('porciento_comision', models.IntegerField(verbose_name='Porciento')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Marca')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='Nombre Comercial')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Tipo de Usuario')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Usuario')),
                ('cedula', models.CharField(max_length=11, verbose_name='Cedula')),
                ('limiteCredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.tipoUsuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_facturacion', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=150)),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Empleados')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id_cafeteria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Nombre de Cafeteria')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Empleados')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Campus')),
            ],
            options={
                'verbose_name': 'Cafeteria',
                'verbose_name_plural': 'Cafeterias',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Articulo')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('existencia', models.IntegerField(max_length=400, verbose_name='Existencia')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Marca')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Proveedor')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='detalleVenta',
            fields=[
                ('id_facturacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Appcafeteria.Factura')),
                ('cantidad', models.IntegerField(max_length=100, verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Articulo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Usuario')),
            ],
            options={
                'verbose_name': 'DetalleFactura',
                'verbose_name_plural': 'DetalleFacturas',
            },
        ),
    ]
