# Generated by Django 2.2.7 on 2019-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='existencia',
            field=models.IntegerField(verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
