# Generated by Django 2.2.7 on 2019-11-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appcafeteria', '0002_auto_20191114_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalle'},
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_facturacion',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_detalleVenta',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle',
            field=models.ManyToManyField(to='Appcafeteria.detalleVenta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Appcafeteria.Usuario'),
            preserve_default=False,
        ),
    ]
