# Generated by Django 2.2.7 on 2019-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcafeteria', '0004_auto_20191114_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='comentario',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
