# Generated by Django 2.2.7 on 2019-11-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcafeteria', '0005_auto_20191114_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='id_articulo',
            new_name='producto_comprado',
        ),
    ]
