# Generated by Django 2.2.5 on 2019-11-15 02:24

import aplicaciones.Appcafeteria.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcafeteria', '0006_auto_20191114_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='existencia',
            field=models.PositiveIntegerField(verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=13, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='porciento_comision',
            field=models.PositiveIntegerField(verbose_name='Porciento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=13, validators=[aplicaciones.Appcafeteria.validators.validate_cedula], verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='limiteCredito',
            field=models.PositiveIntegerField(),
        ),
    ]
