# Generated by Django 2.2.5 on 2019-11-15 04:31

import aplicaciones.Appcafeteria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcafeteria', '0007_auto_20191114_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=13, validators=[aplicaciones.Appcafeteria.validators.validate_cedula], verbose_name='Cedula'),
        ),
    ]
